// WindCharge Station Finder – Sample Station Data
const STATIONS = [
  {
    id: 1,
    name: "Madurai WindCharge Hub",
    city: "Madurai",
    state: "Tamil Nadu",
    lat: 9.9252,
    lng: 78.1198,
    status: "available",
    distance: "2.3 km",
    travelTime: "6 min",
    chargers: 8,
    availableChargers: 5
  },
  {
    id: 2,
    name: "Coimbatore Green Station",
    city: "Coimbatore",
    state: "Tamil Nadu",
    lat: 11.0168,
    lng: 76.9558,
    status: "available",
    distance: "5.1 km",
    travelTime: "12 min",
    chargers: 6,
    availableChargers: 4
  },
  {
    id: 3,
    name: "Bangalore Smart Charge Point",
    city: "Bangalore",
    state: "Karnataka",
    lat: 12.9716,
    lng: 77.5946,
    status: "busy",
    distance: "3.7 km",
    travelTime: "9 min",
    chargers: 10,
    availableChargers: 1
  },
  {
    id: 4,
    name: "Mumbai Coastal Wind Station",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.076,
    lng: 72.8777,
    status: "available",
    distance: "4.5 km",
    travelTime: "11 min",
    chargers: 12,
    availableChargers: 8
  },
  {
    id: 5,
    name: "Delhi Hybrid Wind Station",
    city: "Delhi",
    state: "Delhi",
    lat: 28.7041,
    lng: 77.1025,
    status: "offline",
    distance: "6.2 km",
    travelTime: "15 min",
    chargers: 8,
    availableChargers: 0
  },
  {
    id: 6,
    name: "Chennai Highway WindCharge",
    city: "Chennai",
    state: "Tamil Nadu",
    lat: 13.0827,
    lng: 80.2707,
    status: "available",
    distance: "1.8 km",
    travelTime: "4 min",
    chargers: 6,
    availableChargers: 3
  },
  {
    id: 7,
    name: "Kochi Coastal Charger",
    city: "Kochi",
    state: "Kerala",
    lat: 9.9312,
    lng: 76.2673,
    status: "busy",
    distance: "3.2 km",
    travelTime: "8 min",
    chargers: 4,
    availableChargers: 0
  },
  {
    id: 8,
    name: "Trivandrum Green Hub",
    city: "Thiruvananthapuram",
    state: "Kerala",
    lat: 8.5241,
    lng: 76.9366,
    status: "available",
    distance: "5.8 km",
    travelTime: "14 min",
    chargers: 6,
    availableChargers: 4
  },
  {
    id: 9,
    name: "Jaipur Wind Plaza",
    city: "Jaipur",
    state: "Rajasthan",
    lat: 26.9124,
    lng: 75.7873,
    status: "available",
    distance: "7.1 km",
    travelTime: "18 min",
    chargers: 10,
    availableChargers: 7
  },
  {
    id: 10,
    name: "Jodhpur Desert WindCharge",
    city: "Jodhpur",
    state: "Rajasthan",
    lat: 26.2389,
    lng: 73.0243,
    status: "busy",
    distance: "4.9 km",
    travelTime: "12 min",
    chargers: 6,
    availableChargers: 1
  },
  {
    id: 11,
    name: "Pune Highway Station",
    city: "Pune",
    state: "Maharashtra",
    lat: 18.5204,
    lng: 73.8567,
    status: "available",
    distance: "3.4 km",
    travelTime: "8 min",
    chargers: 8,
    availableChargers: 6
  },
  {
    id: 12,
    name: "Mysore Wind Energy Hub",
    city: "Mysuru",
    state: "Karnataka",
    lat: 12.2958,
    lng: 76.6394,
    status: "available",
    distance: "2.9 km",
    travelTime: "7 min",
    chargers: 4,
    availableChargers: 3
  },
  {
    id: 13,
    name: "Gurgaon Smart Hub",
    city: "Gurugram",
    state: "Delhi",
    lat: 28.4595,
    lng: 77.0266,
    status: "available",
    distance: "5.5 km",
    travelTime: "13 min",
    chargers: 10,
    availableChargers: 6
  },
  {
    id: 14,
    name: "Nagpur Central WindCharge",
    city: "Nagpur",
    state: "Maharashtra",
    lat: 21.1458,
    lng: 79.0882,
    status: "offline",
    distance: "8.3 km",
    travelTime: "20 min",
    chargers: 6,
    availableChargers: 0
  }
];

// Region centers for map zoom
const REGIONS = {
  "All States": { lat: 20.5937, lng: 78.9629, zoom: 5 },
  "Tamil Nadu": { lat: 11.1271, lng: 78.6569, zoom: 7 },
  "Karnataka": { lat: 12.5, lng: 76.5, zoom: 7 },
  "Kerala": { lat: 9.5, lng: 76.5, zoom: 8 },
  "Maharashtra": { lat: 19.5, lng: 75.5, zoom: 7 },
  "Delhi": { lat: 28.6, lng: 77.1, zoom: 10 },
  "Rajasthan": { lat: 26.5, lng: 74.5, zoom: 7 }
};
